### ISSUE TITLE
Last Push Payload Infinite Loop on iOS

### ISSUE THREAD

**Issue by Gabriel-Azevedo** [la-haus/iterable-flutter#35]
Hi everybody,

I was wondering how are you avoiding an infinite loop when using the setNotificationOpenedHandler on iOS. 

Since you get the last push payload every time the app is opened, even if the user already saw the push, every subsequent app open will take them to the push's deep link.

Steps to reproduce:
1. Send a push notification with a deep link payload
2. Tap the notification
3. The app will take the user to the deep link's page (If implemented)
3. Close the app
4. Open the app
5. setNotificationOpenedHandler will be triggered with the last push payload and the app will handle the last push again.
6. The app will take the user to the deep link's page (If implemented)

Steps 4-6 will repeat forever every time the app is opened.

Is this the intended behavior for your application? 

A way to fix this is to stop querying for the last push payload every time the setNotificationOpenedHandler is set and instead only trigger it went the actual system's didReceiveNotification function is called.

I can open a pull request if that makes sense

Thanks for the help.

**Comment by chuac** [comment]
I believe I was running into this issue on Android too, but simply stored the `messageId` from the payload of the previously opened notification to work-around it. Great to see this though!

**Comment by cdmunoz** [comment]
Thank you for writing about it.
I'm going to take a look of this asap and then either fix the issue (if so) taking into consideration Gabriel's fix or probably looking for a different solution.

**Comment by Santi92** [comment]
It's already available in `iterable_flutter: 0.5.4` 🤓
