### ISSUE TITLE
Actively Developed?

### ISSUE THREAD

**Issue by chillbrodev** [la-haus/iterable-flutter#60]
Is this project still actively developed?

**Comment by cdmunoz** [comment]
Hi @chillbrodev 
Yes, it's still active although as we are supporting our main features for our own apps we haven't developed anything besides what we need.
Also, if you have any new feature o fix to push, go ahead!

**Comment by chillbrodev** [comment]
> Hi @chillbrodev
> Yes, it's still active although as we are supporting our main features for our own apps we haven't developed anything besides what we need.
> Also, if you have any new feature o fix to push, go ahead!

Ok good to know, we were looking at using this wrapper for a flutter app and I wanted to make sure it was still being developed. Thanks
