### ISSUE TITLE
iOS: Not sending any data to Iterable

### ISSUE THREAD

**Issue by QoLTech** [la-haus/iterable-flutter#64]
I've got this setup and working for Android and it's great. I have it setup for iOS, but I'm unable to get any data about the device into Iterable. I'm calling IterableFlutter.setEmail(email: "email@email.com") and nothing happens. Every once in awhile I will get it to request permission for Push Notifications, but not often. Even after getting the request and approving, nothing happens in Iterable.

Can anyone confirm that this still works for iOS?

**Comment by QoLTech** [comment]
@danielgomezrico Can you confirm that running the app in example without any changes works for iOS? I can't get the device tokens to register in Iterable with it, but it does work for Android. I call setEmail and it looks like it creates an Iterable entry, but it's entirely empty. On Android it fills out a bunch of data including the FCM token. Do I need to make XCode changes, register something, etc?

I would love to get this implemented for my use-case. I'm testing my changes that add JWT auth to this package, but I can't verify that iOS works at all.

**Comment by danielgomezrico** [comment]
@QoLTech I'm not sure about the app in the example, but we have in production iOS and push works, maybe there's a case that has not been handled? Have you checked iterable logs on the device?

**Comment by QoLTech** [comment]
@danielgomezrico How do I check the iterable logs on the device?

**Comment by danielgomezrico** [comment]
@QoLTech it is working fine? It is not a bug?
